config/routes.rb
Fplaza::Application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :references
  resources :articles
  resources :systems do
    collection do
      get :industrial
      get :home
    end
  end
  
  %w/about design dispatch service contacts/.each do |action|
    get action => "main##{action}"
  end

  root :to => 'main#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
# encoding: utf-8
class Article < ActiveRecord::Base
  attr_accessible :name, :description, :visible, :kind, :image, :image_cache, :position
  mount_uploader :image, ImageUploader

  KINDS = %w/article news/
  KIND_LABELS = {article: 'статья', news: 'новость'}

  scope :articles, -> { where(kind: 'article') }
  scope :news,     -> { where(kind: 'news') }
  scope :visible,  -> { where(visible: true) }

  default_scope order('position desc')
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :description, :logo, :logo_cache, :name, :position
  mount_uploader :logo, ImageUploader

  default_scope order('position desc')
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :name, :phone, :photo, :photo_cache, :post, :position
  mount_uploader :photo, ImageUploader

  default_scope order('position desc')
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :name, :description, :image, :image_cache, :position
  mount_uploader :image, ImageUploader

  default_scope order('position desc')
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :image, :image_cache
  mount_uploader :image, ImageUploader
end

app/models/system.rb
# encoding: utf-8
class System < ActiveRecord::Base
  attr_accessible :name, :description, :kind, :company_id, :parent_id

  acts_as_nested_set
  
  belongs_to :company

  KINDS = %w/industrial home/
  KIND_LABELS = {
    industrial: 'промышленные',
    home: 'бытовые'
  }

  scope :industrial, -> { where(kind: 'industrial') }
  scope :home,       -> { where(kind: 'home') }
end

app/models/text.rb
class Text < ActiveRecord::Base
  attr_accessible :name, :description

  def self.content(name)
    find_by_name(name).try(:description).try(:html_safe)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def show_banner
    @show_banner = true
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @collection = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :show_banner, only: [:index, :about]
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController

  def index
    @collection = Reference.all
  end

  def show
    @reference = Reference.find(params[:id])
  end
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  def industrial
    @companies = []
    @collection = {}
    System.industrial.roots.includes(:company).each do |s|
      @companies << s.company
      @collection[s.company_id] ||= []
      @collection[s.company_id] << s
    end
    @companies.compact!.sort_by!(&:position).reverse!.uniq!
  end

  def home
    @companies = []
    @collection = {}
    System.home.roots.includes(:company).each do |s|
      @companies << s.company
      @collection[s.company_id] ||= []
      @collection[s.company_id] << s
    end
    @companies.compact!.sort_by!(&:position).reverse!.uniq!
  end

  def show
    @system = System.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_banner?
    @show_banner || false
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/articles/index.haml
#content
  %h1 Статьи / Новости
  #articles
    - @collection.each do |article|
      %article
        .article-thumb
          = link_to image_tag(article.image?? article.image.url(:thumb) : 'article.jpg'), article_path(article)
          %span.article-type
            %a{:href => articles_path}=t article.kind
        %header
          %h3= article.name
    %br.clear

- content_for :title, "Статьи / Новости"
- content_for :description, "Статьи и новости компании Forum Plaza"

app/views/articles/show.haml
#content
  %h1= @article.name
  =raw @article.description

- content_for :title, "Статья: #{@article.name}"
- content_for :description, "Статья: #{@article.name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Forum Plaza &bull; #{yield :title}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = yield :script
    = csrf_meta_tags
    %meta(http-equiv="Content-Type" content="text/html; charset=utf-8")
    %meta{:name => "description", :content => yield(:description)}
  %body
    #container
      #header
        #logo= link_to image_tag('logo.jpg', alt: 'Forum Plaza'), root_path
        #menu
          = link_to 'О компании', about_path, class: 'item'
          .dropdown
            = link_to 'Услуги', '#', class: 'item'
            .menu
              .item= link_to 'Проектирование', design_path
              .item= link_to 'Диспетчеризация', dispatch_path
              .item= link_to 'Сервис', service_path
          .dropdown
            = link_to 'Системы', '#', class: 'item'
            .menu
              .item= link_to 'Промышленные', industrial_systems_path
              .item= link_to 'Бытовые', home_systems_path
          = link_to 'Референции', references_path, class: 'item'
          = link_to 'Контакты', contacts_path, class: 'item'
        %br.clear
      #banner.theme-default
        - if show_banner?
          #slider
            - Slide.all.each do |slide|
              = image_tag(slide.image.url, style: 'visibility: hidden;')
      = yield
      #footer
        #stamp_block.footer_block
          = image_tag('stamp.png', alt: 'Forum Plaza')
        .footer_block
          %h4 Forum Plaza
          .links_block
            = link_to 'О компании', about_path
            %br
            = link_to 'Новости/Статьи', articles_path
            %br
            = link_to 'Проектирование', design_path
            %br
            = link_to 'Диспетчеризация', dispatch_path
          .links_block
            = link_to 'Сервис', service_path
            %br
            = link_to 'Промышленные системы', industrial_systems_path
            = link_to 'Бытовые системы', home_systems_path
            = link_to 'Референции', references_path
        #marker_block= link_to image_tag('marker.png'), contacts_path
        .footer_block
          %h4 Офис
          Украина 08130 Киев
          %br
          ул. Петропавловская, 14-Е
          %br
          ТЦ "Диамант" 3 этаж
          %br
          E-mail: office@forumplaza.com.ua
        #phone_block.footer_block (044) 450-05-10
    :javascript

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-45486303-1']);
      _gaq.push(['_setDomainName', 'forumplaza.com.ua']);
      _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();


      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter22820984 = new Ya.Metrika({id:22820984,
                          webvisor:true,
                          clickmap:true,
                          trackLinks:true,
                          accurateTrackBounce:true});
              } catch(e) { }
          });

          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks");

app/views/main/about.haml
#content
  %h1 О компании
  %p=raw ::Text.content('about')

- content_for :title, "О компании"
- content_for :description, "Форум-Плаза – компания с многолетним опытом внедрения климатических систем на рынке Украины."

app/views/main/contacts.haml
#content
  %h1 Контакты
  #contacts
    - Contact.all.in_groups_of(4) do |group|
      - group.each do |contact|
        - next if contact.nil?
        .foto
          = image_tag contact.photo.url
          %br/
          %b= contact.name
          %br/
          = contact.post
          %br/
          Моб.: #{contact.phone}
          %br/
          E-mail: #{contact.email}
      %br.clear/
  #location
    %h1 Офис
    #address
      Украина 08310 Киев
      %br/
      Большая Окружная дорога
      %br/
      Петропавловская Борщаговка,
      %br/
      ул. Петропавловская 14-Е
    #contact_info
      ТЦ «Диамант»
      %br/
      тел/факс: #{ ::Text.content('phone') }
      %br/
      E-mail: #{ ::Text.content('email') }
    #map

- content_for :script, javascript_include_tag('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&language=ru', 'map.js')
- content_for :title, "Контакты"
- content_for :description, "Украина, Киев, Большая Окружная дорога, Петропавловская Борщаговка, ул. Петропавловская 14-Е"

app/views/main/design.haml
#content
  .badge= image_tag "project_inactive.jpg"
  %h1 Проектирование
  %p=raw ::Text.content('design')

- content_for :title, "Проектирование"
- content_for :description, "Проектные работы любой сложности, мы осуществляем анализ и экспер­тизу готовых проектных решений. Монтажная группа компании произ­водит высококачественный монтаж климатического оборудования."

app/views/main/dispatch.haml
#content
  .badge= image_tag "dispetc_inactive.jpg"
  %h1 Диспетчеризация
  %p=raw ::Text.content('dispatch')

- content_for :title, "Диспетчеризация"
- content_for :description, "Системы интегрированного управле­ния позволяют эффективно управлять и контролировать работу систем кондиционирования. Доступ в интер­нет, различные режимы работы, индивидуальные настройки."

app/views/main/index.haml
#equipment
  %h3 Эксклюзивный партнер
  %a{:href => industrial_systems_path}
    %img#samsung{:alt => "Samsung", :src => "/assets/samsung.png"}/
  %a{:href => home_systems_path}
    %img#unico{:alt => "Unico", :src => "/assets/unico.png"}/
  %br.clear/
#systems
  #prom
    %a{:href => industrial_systems_path}
      .img
      .system_label
        %h2> Промышленные
        климатические системы
  #home
    %a{:href => home_systems_path}
      .img
      .system_label
        %h2> Бытовые
        климатические системы
  %br.clear/
#service
  .service_block
    %a{:href => design_path}
      #project.img
      %h2 Проектирование
      %p Проектные работы любой сложности, мы осуществляем анализ и экспер&shy;тизу готовых проектных решений. Монтажная группа компании произ&shy;водит высококачественный монтаж климатического оборудования.
  .service_block
    %a{:href => dispatch_path}
      #dispec.img
      %h2 Диспетчеризация
      %p Системы интегрированного управле&shy;ния позволяют эффективно управлять и контролировать работу систем кондиционирования. Доступ в интер&shy;нет, различные режимы работы, индивидуальные настройки.
  .service_block
    %a{:href => service_path}
      #serv.img
      %h2 Сервис
      %p Регулярное обслуживание  систем вентиляции, отопления и кондицио&shy;нирования предупреждает серьез&shy;ные поломки, влекущие за собой соответствующие внеплановые за&shy;траты.
  %br.clear/
#articles
  - Article.visible.each do |article|
    %article
      .article-thumb
        = link_to image_tag(article.image?? article.image.url(:thumb) : 'article.jpg'), article_path(article)
        %span.article-type
          %a{:href => articles_path}=t article.kind
      %header
        %h3= article.name
  %br.clear/

- content_for :title, "Промышленные и бытовые климатические ситемы. Проектирование, диспетчеризация, сервис"

app/views/main/service.haml
#content
  .badge= image_tag "service_inactive.jpg"
  %h1 Сервис
  %p=raw ::Text.content('service')

- content_for :title, "Сервис"
- content_for :description, "Регулярное обслуживание  систем вентиляции, отопления и кондицио­нирования предупреждает серьез­ные поломки, влекущие за собой соответствующие внеплановые за­траты."

app/views/references/index.haml
#content
  %h1 Референции
  - @collection.each do |item|
    %article.reference
      .article-thumb
        - if item.image?
          = link_to image_tag(item.image.url(:pano)), reference_path(item)
        %span.article-type= link_to(item.name, [item])

- content_for :title, "Референции"
- content_for :description, "Референции"

app/views/references/show.haml
#content
  %h1= @reference.name
  =raw @reference.description

- content_for :title, "Референция: #{@reference.name}"
- content_for :description, "Референция: #{@reference.name}"

app/views/systems/_list.haml
- companies.each do |company|
  .company
    = image_tag(company.logo.url)
    %p 
      %b= company.name
      – #{company.description}
    %ul
      - collection[company.id].each do |system|
        %li= link_to system.name, [system]

app/views/systems/home.haml
#content
  .badge= image_tag "butovue_sitemu_inactive.jpg"
  %h1 Бытовые климатические системы
  = render partial: 'list', locals: { collection: @collection, companies: @companies }

- content_for :title, "Бытовые климатические системы"
- content_for :description, "Бытовые климатические системы"

app/views/systems/industrial.haml
#content
  .badge= image_tag "Prom_sistemu_inactive.jpg"
  %h1 Промышленные климатические системы
  = render partial: 'list', locals: { collection: @collection, companies: @companies }

- content_for :title, "Промышленные климатические системы"
- content_for :description, "Промышленные климатические системы"

app/views/systems/show.haml
#content
  %h1= @system.self_and_ancestors.map(&:name).join(' / ')
  %p= @system.description.html_safe
  %ul
    - @system.children.each do |system|
      %li= link_to system.name, [system]

- content_for :title, "Климатическая система: #{@system.name}"
- content_for :description, "Климатическая система: #{@system.name}"